### ISSUE TITLE
Temporary override target incorrectly displayed when using mmol/l

### ISSUE THREAD

**Issue by bartsopers** [LoopKit/Loop#1016]
**Describe the bug**
When a temporary override is set, the target BG is displayed incorrectly in the BG graph. It's displayed way lower than the actual target.

**To Reproduce**
1. Set a temporary override with BG target override (either custom or predefined)
2. The target BG is displayed incorrectly in the BG graph. (please see attached screenshots)

**Expected behavior**
The temporary target is displayed correctly.

**Screenshots**
![IMG_1478](https://user-images.githubusercontent.com/15631208/61453480-7535f080-a95e-11e9-81dd-ad471215f5dc.PNG)
![IMG_1479](https://user-images.githubusercontent.com/15631208/61453481-7535f080-a95e-11e9-99c1-b76f93bd015d.PNG)

**Phone**
 - Hardware: iPhone XR
 - OS Version: iOS 12.3.1

**Loop Version**
 - Version Number: 1.10.0DEV
 - Repo: omnipod-testing-integrate

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

**Additional context**
Using mmol/l

**Comment by amdee1** [comment]
I noticed similar behavior, using mmol/l. No matter what the target range is, or if I left target range blank.

**Comment by amdee1** [comment]
Also same issue, if I set a pre-meal target.

**Comment by ps2** [comment]
Fixed with #1023

**Comment by bartsopers** [comment]
omnipod_reservoir_over50

**Comment by bartsopers** [comment]
I just rebuilt Loop and this problem still exists for me (for both custom and predefined overrides).

**Comment by Kdisimone** [comment]
@bartsopers what branch did you build with? Did you download a new dev download and build with that?

**Comment by bartsopers** [comment]
@Kdisimone I’m on the dev branch and updated with git

**Comment by ps2** [comment]
This fixes only part of the problem. There is a bigger fix needed for overrides to store the units that the overrides are defined in. Users with their overrides currently defined in mmol/L will have display issues.

**Comment by alevar1975** [comment]
Hi Katie,

 

I'm Alen and I have been using Loop since September last year. I have realised so far that there is a growing number of people using Loop in Germany. Therefore, I do see a need to translate and localise the LoopDocs into German.

 

I already translated the first page into German, https://loopkit.github.io/loopdocs, and I opended a pull request on GitHub. The pull request has not benn reviewed yet. Franjky, I'm not sure whether this is the right way for the translation process because in case you accept the changes, the English version would disappear.

 

I finished a translation of the following page today: https://kdisimone.github.io/looptips/settings/settings

 

You will find the doc attached. Please let me know if you are interested to have the LoopDocs translated into German. If so, you can give me hint how to go on with the translation. I would be grateful if you could let me know how the correct GitHub proces is.

 

Best wishes,

 

Alen

**Comment by bartsopers** [comment]
I noticed this has been fixed by a recent PR. Awesome, thanks a lot @ps2!
