### ISSUE TITLE
Show previous carb entries that are active after midnight

### ISSUE THREAD

**Issue by elnjensen** [LoopKit/Loop#840]
Since Loop resets the carb display at midnight, it is not possible after that to edit a previous entry, even if the carbs are still active. This limits a user's options for tweaking carb amount or timing if it turns out to be incorrect, if the absorption window crosses the midnight boundary. 

A fix could be to always show any entry that hasn't yet expired.  (This is related to #681, but distinct as this is not only about the display, but editing of active carbs).

**Comment by cfaagaard** [comment]
Maybe ICE-result could be sent to Nightscout? Maybe updating the treatment with actual carb-entry. Then one could see it in the treatment-report fx in the note field. See picture.
![ice](https://user-images.githubusercontent.com/25353502/47673195-397eaf00-dbb4-11e8-96e3-e144dbf30cd8.png)

**Comment by Nightfoxy** [comment]
I believe this issue has been addressed, but I think the absorption for the entry that is from the previous day (prior to midnight) is not using the ISF from yesterday, but switches to using the ISF defined at midnight for absorption. I think this is a separate issue.

Should this issue be closed?

**Comment by NightScoutForSeb** [comment]
I still experience this frequently with high fat/high protein boluses from the night before that were set to 6h absorption but should have been 8h absorption. I can’t go back and edit them after the fact.
