### ISSUE TITLE
Bolus not delivered recorded as IOB

### ISSUE THREAD

**Issue by sjolundjohn** [LoopKit/Loop#983]
I had a very concerning event today - hopefully I did something wrong.

This is for the Omnipod loop.

I took screenshots after the fact to try to illustrate.

The sequence of events:

1) I entered carbs for lunch
2) Loop provided a recommendation for the bolus which I clicked to start a bolus.
3) A few seconds later I get a notification on my phone that the bolus may have failed (image #1)
4) Looking at the Loop app, it said that the bolus was in the process of being delivered.
5) I couldn't hear the clicks from the Omnipod clicking - so it didn't, in fact, seem like any bolus was being delivered
6) Because I couldn't hear any clicks, I canceled the bolus from the Loop app.

RESULT:
a) Despite canceling the app, the next time the algo ran, it indicated that I had the full bolus onboard (Image #2). You can see it says that I had 6.22 units IOB (before starting bolus I had a negative IOB). This does not seem right

b) I checked the insulin delivery status, and you can see that the bolus was interrupted (Image #3)

c) When looking at the event log, I can confirm that the bolus was interrupted (Image #4)

d) When looking at the insulin delivery log, it hadn't been updated for 2 hours (Image #5)

QUESTIONS:
Question #1- Does the bolus status on the Loop app actually provides real-time updates about bolus OR is it an estimation.
Question #2- Why would Loop not be able to be aware that no bolus was actually delivered. It told me I had a lot more IOB on board then I did, which would cause significant hyperglycemia
Question #3- Why is the Insulin Delivery log not updated with status as the rest of the app is?

![IMG_3856](https://user-images.githubusercontent.com/17986135/58663699-e9023800-82e1-11e9-9aa3-7a05ccee1ea3.png)

![IMG_3857](https://user-images.githubusercontent.com/17986135/58663709-ef90af80-82e1-11e9-8061-e33a4d104b64.png)

![IMG_3854](https://user-images.githubusercontent.com/17986135/58663721-f61f2700-82e1-11e9-9ef5-f9319bc90092.png)

![IMG_3855](https://user-images.githubusercontent.com/17986135/58663726-f91a1780-82e1-11e9-9e11-523df26d6134.png)

![IMG_3853](https://user-images.githubusercontent.com/17986135/58663693-e1db2a00-82e1-11e9-9935-c020e36ed31a.png)

**Comment by ps2** [comment]
There is a fix in the works for this. There will still be cases where we have an uncertain bolus that we don't know if it was delivered or not, and in that case we need to assume it was.  But in this case, canceling an uncertain bolus, we should be able to check in with the pod and verify bolus status.

**Comment by johntwohy** [comment]
I had a very similar issue happen yesterday., however with one notable difference.

1) Attempted to give bolus for meal, but got the interrupted bolus error.
2) Pump was not clicking, so assumed bolus did not go through and canceled bolus.
3) Carbs and insulin were still recorded as on board. I deleted the bolus event (insulin delivery > event history > delete event) thinking this would delete the insulin from loops memory, but it did not

4) NOTABLE DIFFERENCE: I then noticed that loop recorded a temporary basal of 35.58U/hour at the same time (1st figure below). I think (but am not certain) this appears to have been included in the IOB (2nd figure below).
5) However, I'm pretty confident this temp basal did not actual happen, since it was not recorded in event history (2nd figure below), and I have a max basal rate limit of 2.5U/hr (3rd figure below).

Didn't cause any issues. I just went off closed loop for a while until the IOB reverted to normal. 

One thought on the fix: It makes sense to cautiously assume that the bolus went through, but could the user be able to tell Loop that the bolus did not go through (based on not hearing any clicks)?

![image](https://user-images.githubusercontent.com/51167446/58824346-7bb41700-8601-11e9-851c-acf427b0f188.png)

![image](https://user-images.githubusercontent.com/51167446/58824354-81a9f800-8601-11e9-8482-f3e71802c9c3.png)

![image](https://user-images.githubusercontent.com/51167446/58824364-85d61580-8601-11e9-802f-812336140bd9.png)

**Comment by sbalint** [comment]
I had this same “may not have succeeded” issue happen just now. Didn’t cancel the bolus. It was 4 unit bolus and I watched the app go through the delivery action with no clicks. Didn’t realize this was a possibility/known issue but it has definitely happened to me a few times previously.

**Comment by vnephologist** [comment]
Any chance this one is fixed yet? Just ran into it on 1.10.0. Thanks!

**Comment by yaelirt** [comment]
Had this issue today. Jojo branch. Entered a bolus that failed (had a notification and also no clicks), gave another one and deleted the first entry, but the active insulin is still calculated as if both boluses were delivered.

**Comment by bkohrs** [comment]
I ran into this today. I entered a bolus and it failed. I didn't know how to handle it, and so I removed the entry from the Insulin Delivery table, but it still shows in the IOB. I bolused again to get the insulin delivered, and my IOB now shows both boluses. Is this a bug that needs fixed, or should it be handled differently?

**Comment by Kdisimone** [comment]
@bkohrs update to dev branch (and remove the entry from Health app too if you run into this before updating)

**Comment by Kdisimone** [comment]
closing as the above referenced PR resolves the issue
